[package]
name = "stacktrace"
version = "0.1.0"
authors = ["Edward Pierzchalski <e.a.pierzchalski@gmail.com>"]

[dependencies]
backtrace = "0.1.8"
libc = "0.2.4"

[[example]]
name = "ex1"
path = "examples/ex1/main.rs"
